### ISSUE TITLE
kuksa-client docker image does not work

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#163]
```
> docker run -it amd64/kuksa-client:441558b
Welcome to kuksa viss client 0.1.6

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/kuksa_viss_client/kuksa_viss_client/__main__.py", line 257, in <module>
    sys.exit(main())
  File "/kuksa_viss_client/kuksa_viss_client/__main__.py", line 253, in main
    clientApp = TestClient()
  File "/kuksa_viss_client/kuksa_viss_client/__main__.py", line 108, in __init__
    with open(os.path.join(scriptDir, 'logo'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/kuksa_viss_client/kuksa_viss_client/logo'
```

**Comment by SebastianSchildt** [comment]
We need more tests 😭

**Comment by callalilychen** [comment]
totally agree, plan it pls!
Tested on my pc, it works, but on jenkins produced containers do not work!
