### ISSUE TITLE
memory issue when stop `kuksa-val-server`

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#225]
destruct call in ctrlC handle seems to be illegal. see gdb output:
```
(gdb) sign SIGINT
Continuing with signal SIGINT.
munmap_chunk(): invalid pointer

Thread 1 "kuksa-val-serve" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7558859 in __GI_abort () at abort.c:79
#2  0x00007ffff75c33ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff76ed285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff75cb47c in malloc_printerr (str=str@entry=0x7ffff76ef1e0 "munmap_chunk(): invalid pointer") at malloc.c:5347
#4  0x00007ffff75cb6cc in munmap_chunk (p=<optimized out>) at malloc.c:2830
#5  0x00005555556c7077 in VssDatabase::~VssDatabase (this=0x555555be3100, __in_chrg=<optimized out>) at /home/chw2lr/code/kuksa.val2/src/VssDatabase.cpp:43
#6  0x0000555555587f52 in ctrlC_Handler (signal=2) at /home/chw2lr/code/kuksa.val2/src/main.cpp:58
#7  <signal handler called>
#8  main (argc=1, argv=0x7fffffffe0e8) at /home/chw2lr/code/kuksa.val2/src/main.cpp:268
```

**Comment by wenwenchenbosch** [comment]
@linussieweke If you are interested, we can have a look of the problem together.
