### ISSUE TITLE
Unable to connect kuksa databroker on localhost:55556

### ISSUE THREAD

**Issue by meSATYA** [eclipse/kuksa.val#505]
Getting these errors while running a python client which connects to kuksa databroker.

Both kuksa databroker & the python client are running as docker containers inside a docker-compose file.

[09/Mar/2023 12:20:27] "GET /receive_command/Vehicle.Speed/120 HTTP/1.1" 500 -
2023-03-09 17:50:27 Traceback (most recent call last):
2023-03-09 17:50:27   File "/venv/lib/python3.10/site-packages/kuksa_client/grpc/__init__.py", line 785, in get_server_info
2023-03-09 17:50:27     resp = self.client_stub.GetServerInfo(req, **rpc_kwargs)
2023-03-09 17:50:27   File "/venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
2023-03-09 17:50:27     return _end_unary_response_blocking(state, call, False, None)
2023-03-09 17:50:27   File "/venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
2023-03-09 17:50:27     raise _InactiveRpcError(state)
2023-03-09 17:50:27 grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
2023-03-09 17:50:27     status = StatusCode.UNAVAILABLE
2023-03-09 17:50:27     details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:[127.0.0.1:55556](https://127.0.0.1:55556/): Failed to connect to remote host: Connection refused"
2023-03-09 17:50:27     debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:[127.0.0.1:55556](https://127.0.0.1:55556/): Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-03-09T12:20:27.852128758+00:00"}"

Can someone please assist?

**Comment by lukasmittag** [comment]
Hey,

Could you maybe share you're docker-compose file? Have you set network_mode: host?

**Comment by meSATYA** [comment]
Able to access after using dns:///<host_name> url. Thanks
